### ISSUE TITLE
What are the 10 domains covered in this dataset?

### ISSUE THREAD

**Issue by chikubee** [clinc/oos-eval#3]
Could not find the answer to this question in the documentation.
What are the different domains covered in the dataset?
Is there a domain - intent mapping, to extract the data of interest?

**Comment by gxlarson** [comment]
The 10 domains along with the corresponding intents (and examples) can be found in this pdf file (starting with the second page): https://github.com/clinc/oos-eval/blob/master/supplementary.pdf

**Comment by chikubee** [comment]
@gxlarson thank you for your quick response
