### ISSUE TITLE
Question about threshold in paper

### ISSUE THREAD

**Issue by duongkstn** [clinc/oos-eval#4]
Hi,
In paper "An Evaluation Dataset for Intent Classification and Out-of-Scope Prediction", you made comparisons between three approaches: **oos-train**, **oss-threshold** and **oss-binary**. 
But the paper did not clearly tell which threshold was used ? 0.5, 0.6, ....

Can you please give me that information ? 
Rgds,

**Comment by gxlarson** [comment]
Please see closed issue #1 . We didn't use a single threshold for the experiments. Instead, the threshold was chosen for each classifier during cross validation. I no longer have the information for what the exact threshold values were, unfortunately.
